# Generated by Django 2.2 on 2019-04-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todolist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.CharField(default='guest', max_length=250),
        ),
    ]
